### ISSUE TITLE
Bug on "chips" sample: the EditText doesn't allow to remove the chip right away

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [ricknout/android-mdc-theming#1]
When you go to this:

![image](https://user-images.githubusercontent.com/5357526/58242931-5fd68880-7d58-11e9-8b1e-8bbd1370b33b.png)

And then you press backspace, it won't go away. You need to press it multiple times.

See video:
[device-2019-05-23-124415.zip](https://github.com/ricknout/android-mdc-theming/files/3211409/device-2019-05-23-124415.zip)

**Comment by ricknout** [comment]
Hmm thanks, I will check it out.

FWIW, the sample was inspired by the one here:
https://material.io/develop/android/components/chip/

**Comment by ricknout** [comment]
So it seems quite a bit of extra work is required to correct this, see:
https://stackoverflow.com/questions/52942628/delete-entire-imagespan-when-the-part-of-it-is-deleted
https://stackoverflow.com/questions/19534427/edittext-with-spannablestringbuilder-and-imagespan-doesnt-works-fine

It's a bit outside of the scope of this repository, so I'm going to close the issue.

**Comment by AndroidDeveloperLB** [comment]
They explain about emojis, that it shouldn't offer auto-suggestions.
But I've tested now on chatting apps, and I don't see such issues.
And the first link you wrote about doesn't even have a solution.

**Comment by ricknout** [comment]
They explain using `ImageSpan` (which can also be used for emoji and other things). If you look at `ChipActivity`, this is the same class used to render a `ChipDrawable` in an `EditText`.

**Comment by AndroidDeveloperLB** [comment]
Can you please fix this issue on the sample then? To show how it should be done without the extra spaces, just like on other apps?
You can see on Gmail, for example, that it doesn't add extra spaces. A single backspace is enough to remove the chip.

**Comment by ricknout** [comment]
It's not a priority for me at the moment, but I will get to it at some point. Note that I would basically adapt those two links I sent above, so I would suggest trying it out in the mean time.

**Comment by AndroidDeveloperLB** [comment]
OK thank you.
I hope you succeed, and that you won't need workarounds.
