### ISSUE TITLE
Question: is it possible to use ExtendedFloatingActionButton to have a progress bar within?

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [ricknout/android-mdc-theming#2]
This way, it can have multiple states for doing something, and an animation between the states.
Example:
1. "Download" (press to initialize downloading of something)
2. progress bar (to show the download progress)
3. "Retry" (failed to download, press again to start)
4. "Done" (icon of "V" , to show that it's done).

**Comment by ricknout** [comment]
The only way I can think of is to use an `AnimatedVectorDrawable` as the `ExtendedFloatingActionButton` icon,  but these do not support setting a progress on the animation as of now.

It might be worth checking out a library called Kyrie:
https://www.androiddesignpatterns.com/2018/03/introducing-kyrie-animated-vector-drawables.html

**Comment by AndroidDeveloperLB** [comment]
I see. Thank you
