### ISSUE TITLE
Question: is it possible to use a theme based on OS settings?

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [ricknout/android-mdc-theming#4]
On Android 8.1 (and maybe 9.0) there is a way to set a wallpaper or live wallpaper that will (try to) change the theme of the OS, making it dark or not.

Is it possible to adjust the UI based on it? If so, how can I do it and detect the theme?

I know that on Android Q it should be possible, but what about previous versions?

**Comment by ricknout** [comment]
Hi @AndroidDeveloperLB,

Yes, you are correct. There is also a new setting in Android Q to enable this with a setting (https://developer.android.com/preview/features/darktheme).

I have not yet updated this repository to support these changes. Please can you make a GitHub issue for is on this repository?

Thanks!

**Comment by AndroidDeveloperLB** [comment]
I don't know of a repository to demonstrate it, but here. I've made a sample for you:

[My Application.zip](https://github.com/ricknout/android-mdc-theming/files/3224720/My.Application.zip)

video:

[2019-05-27_21-26-38.zip](https://github.com/ricknout/android-mdc-theming/files/3224724/2019-05-27_21-26-38.zip)

Based on [here](https://stackoverflow.com/a/56036734/878126)

My question was about older versions though.
Do you know perhaps if it's possible to check what is the theme or colors of the OS, on Android 8.1 and above?

**Comment by ricknout** [comment]
Dark theming support has been added:
https://github.com/ricknout/android-mdc-theming/commit/0a1147e790f370d13813a20d12fa01dd4c21662e

**Comment by AndroidDeveloperLB** [comment]
Do you know though if it's possible to handle older Android versions?
Meaning to query which theme/colors are used?

**Comment by ricknout** [comment]
Dark Theming support relies on DayNight functionality in AppCompat. It does handle older versions of Android, but the user cannot change anything in settings (you would have to provide your own in-app toggle for this).

With regards to querying which mode you're currently in (i.e. Either light or dark theme) see:
https://link.medium.com/IeSoyG3JaX

**Comment by AndroidDeveloperLB** [comment]
I've actually read this article already, but it doesn't say anything about detection on older Android version (9, 8.1 ...).
Are you sure it works there too?
As I remember (of what I've tested) , this API is only for Q.
